In [107]:
!pip install --quiet pandas numpy sqlalchemy openpyxl duckdb psycopg2-binary

In [3]:
import pandas as pd

# Importation des données et formatage en parquet

Deux fichiers de données : 

- Un fichier de données RH avec le nom des employé et leurs infos
- Un fichier de données sur les pratiques sportives de chacun des employé (relié avec l'ID salarié)

## Fichier RH

In [4]:
data_rh = pd.read_excel('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/Données+RH.xlsx')

In [5]:
data_rh

,ID salarié,Nom,Prénom,Date de naissance,BU,Date d'embauche,Salaire brut,Type de contrat,Nombre de jours de CP,Adresse du domicile,Moyen de déplacement
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running
...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running
158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique
159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres

In [15]:
data_rh.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID salarié             161 non-null    int64
 1   Nom                    161 non-null    str
 2   Prénom                 161 non-null    str
 3   Date de naissance      161 non-null    datetime64[us]
 4   BU                     161 non-null    str
 5   Date d'embauche        161 non-null    datetime64[us]
 6   Salaire brut           161 non-null    int64
 7   Type de contrat        161 non-null    str
 8   Nombre de jours de CP  161 non-null    int64
 9   Adresse du domicile    161 non-null    str
 10  Moyen de déplacement   161 non-null    str
dtypes: datetime64[us](2), int64(3), str(6)
memory usage: 14.0 KB

In [9]:
data_rh.to_json('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/processed/donnees_rh_processed.json', index=False)

/tmp/ipykernel_13093/235700162.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  data_rh.to_json('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/processed/donnees_rh_processed.json', index=False)

## Fichier Sport

In [12]:
data_sport = pd.read_excel('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/Données+Sportive.xlsx')

In [ ]:
data_sport

     ID salarié Pratique d'un sport
0         59019                 NaN
1         19841                 NaN
2         56482              Tennis
3         21886                 NaN
4         81001                 NaN
..          ...                 ...
156       18941              Runing
157       81676              Tennis
158       27069              Runing
159       30256                 NaN
160       94680            Natation

[161 rows x 2 columns]

In [16]:
data_sport.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID salarié           161 non-null    int64
 1   Pratique d'un sport  95 non-null     str
dtypes: int64(1), str(1)
memory usage: 2.6 KB

In [14]:
data_sport.to_json('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/processed/donnees_sport_processed.json', index=False)

## Création du tableau complet

In [22]:
data_rh_sport = pd.merge(data_rh, data_sport, on='ID salarié', how='left')

In [ ]:
data_rh_sport

,ID salarié,Nom,Prénom,Date de naissance,BU,Date d'embauche,Salaire brut,Type de contrat,Nombre de jours de CP,Adresse du domicile,Moyen de déplacement,Pratique d'un sport
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun,NaN
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique,NaN
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique,Tennis
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running,NaN
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres,Runing
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running,Tennis
158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique,Runing
159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique,NaN
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres,Natation

In [24]:
data_rh_sport.to_json('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/processed/donnees_rh_sport_processed.json', index=False)

/tmp/ipykernel_13093/3944058782.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  data_rh_sport.to_json('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/processed/donnees_rh_sport_processed.json', index=False)

## Evaluation de la qualité des données

In [55]:
## Proportion de doublons dans les données fusionnées par colonnes

doublons_proportion = data_rh_sport.duplicated().mean()
doublons_proportion

np.float64(0.0)

# Evaluation de la prime de 5 %

In [26]:
data_rh_sport["Moyen de déplacement"].unique()

<StringArray>
[         'Transports en commun', 'véhicule thermique/électrique',
                'Marche/running',       'Vélo/Trottinette/Autres']
Length: 4, dtype: str

In [ ]:
# Récupération des salariés qui viennent au travaille autrement qu'avec un véhicule thermique ou transports en commun ('Marche/running' ou 'Vélo/Trottinette/Autres')
data_rh_sport_prime = data_rh_sport[(data_rh_sport["Moyen de déplacement"] == "Marche/running") | (data_rh_sport["Moyen de déplacement"] == "Vélo/Trottinette/Autres")]

In [28]:
data_rh_sport_prime

,ID salarié,Nom,Prénom,Date de naissance,BU,Date d'embauche,Salaire brut,Type de contrat,Nombre de jours de CP,Adresse du domicile,Moyen de déplacement,Pratique d'un sport
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running,NaN
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running,NaN
5,17757,Bazin,Margaret,1982-11-24,Support,2023-04-17,31460,CDI,25,"Av. de La Mer, 34470 Pérols",Vélo/Trottinette/Autres,Badminton
9,62296,Chauvin,Zakaria,1987-10-02,Finance,2024-11-23,68680,CDD,26,"31 Av. Grassion Cibrand, 34130 Mauguio",Vélo/Trottinette/Autres,NaN
12,18246,Tessier,Francoise,1986-11-11,Ventes,2025-01-11,30680,CDI,28,"181 Av. de la Gare, 34970 Lattes",Vélo/Trottinette/Autres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
154,42960,Normand,Michel,1994-10-26,Ventes,2025-01-10,26320,CDD,29,"17 Rue Maguelone, 34250 Palavas-les-Flots",Vélo/Trottinette/Autres,Runing
155,13780,Renard,Sylvain,1982-11-29,Finance,2024-04-11,60200,CDI,25,"56 Imp. Robespierre, 34130 Mauguio",Vélo/Trottinette/Autres,NaN
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres,Runing
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running,Tennis
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres,Natation

In [30]:
# Calcul de la prime aux salariés éligibles 

data_rh_sport_prime["Prime"] = data_rh_sport_prime["Salaire brut"] * 0.05
data_rh_sport_prime

,ID salarié,Nom,Prénom,Date de naissance,BU,Date d'embauche,Salaire brut,Type de contrat,Nombre de jours de CP,Adresse du domicile,Moyen de déplacement,Pratique d'un sport,Prime
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running,NaN,3516.0
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running,NaN,2343.5
5,17757,Bazin,Margaret,1982-11-24,Support,2023-04-17,31460,CDI,25,"Av. de La Mer, 34470 Pérols",Vélo/Trottinette/Autres,Badminton,1573.0
9,62296,Chauvin,Zakaria,1987-10-02,Finance,2024-11-23,68680,CDD,26,"31 Av. Grassion Cibrand, 34130 Mauguio",Vélo/Trottinette/Autres,NaN,3434.0
12,18246,Tessier,Francoise,1986-11-11,Ventes,2025-01-11,30680,CDI,28,"181 Av. de la Gare, 34970 Lattes",Vélo/Trottinette/Autres,NaN,1534.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,42960,Normand,Michel,1994-10-26,Ventes,2025-01-10,26320,CDD,29,"17 Rue Maguelone, 34250 Palavas-les-Flots",Vélo/Trottinette/Autres,Runing,1316.0
155,13780,Renard,Sylvain,1982-11-29,Finance,2024-04-11,60200,CDI,25,"56 Imp. Robespierre, 34130 Mauguio",Vélo/Trottinette/Autres,NaN,3010.0
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres,Runing,2995.5
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running,Tennis,2421.5
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres,Natation,3209.0

In [34]:
# Calcul du cout total de la prime pour l'entreprise

cout_total_prime = data_rh_sport_prime["Prime"].sum()
print("Le coût total brut de la prime pour l'entreprise est de : ", cout_total_prime)

Le coût total brut de la prime pour l'entreprise est de :  172482.5

# Evaluation des journées bien être

In [35]:
data_rh_sport

,ID salarié,Nom,Prénom,Date de naissance,BU,Date d'embauche,Salaire brut,Type de contrat,Nombre de jours de CP,Adresse du domicile,Moyen de déplacement,Pratique d'un sport
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun,NaN
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique,NaN
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique,Tennis
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running,NaN
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres,Runing
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running,Tennis
158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique,Runing
159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique,NaN
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres,Natation

In [39]:
data_rh_sport["jour bien etre"] = 0

In [47]:
# Attribuer 5 jours de bien-être aux salariés qui pratiquent un sport (champ non NaN)

data_rh_sport["jour bien etre"] = data_rh_sport["Pratique d'un sport"].notna().apply(lambda x: 5 if x else 0)

In [48]:
data_rh_sport

,ID salarié,Nom,Prénom,Date de naissance,BU,Date d'embauche,Salaire brut,Type de contrat,Nombre de jours de CP,Adresse du domicile,Moyen de déplacement,Pratique d'un sport,jour bien etre
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun,NaN,0
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique,NaN,0
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique,Tennis,5
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running,NaN,0
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres,Runing,5
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running,Tennis,5
158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique,Runing,5
159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique,NaN,0
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres,Natation,5

In [49]:
data_rh_sport["CP Total"] = data_rh_sport["Nombre de jours de CP"] + data_rh_sport["jour bien etre"]

In [50]:
data_rh_sport

,ID salarié,Nom,Prénom,Date de naissance,BU,Date d'embauche,Salaire brut,Type de contrat,Nombre de jours de CP,Adresse du domicile,Moyen de déplacement,Pratique d'un sport,jour bien etre,CP Total
0,59019,Colin,Audrey,1990-07-06,Marketing,2020-12-14,30940,CDI,29,"128 Rue du Port, 34000 Frontignan",Transports en commun,NaN,0,29
1,19841,Ledoux,Monique,1962-01-06,R&D,2020-07-07,74360,CDI,26,"68 Rue du Port, 34970 Saint-Clément-de-Rivière",véhicule thermique/électrique,NaN,0,26
2,56482,Dumont,Michelle,1976-08-09,Ventes,2022-03-29,51390,CDI,27,"100 Av. de la Gare, 30900 Nîmes",véhicule thermique/électrique,Tennis,5,32
3,21886,Toussaint,Judith,1962-09-10,Support,2021-12-12,70320,CDI,29,"53 Av. de la Gare, 34970 Lattes",Marche/running,NaN,0,29
4,81001,Bailly,Michelle,1975-04-20,Ventes,2025-02-19,46870,CDD,29,"74 Rue des Fleurs, 34970 Lattes",Marche/running,NaN,0,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,18941,Guillou,Gilles,1986-12-23,Finance,2025-02-27,59910,CDI,29,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",Vélo/Trottinette/Autres,Runing,5,34
157,81676,Breton,Jeannine,1966-06-24,Ventes,2022-01-22,48430,CDI,29,"27 Av. du Général Leclerc, 34470 Pérols",Marche/running,Tennis,5,34
158,27069,Delahaye,Philippe,1996-09-10,Support,2020-11-27,56380,CDI,29,"59 Chem. des Pins, 34170 Castelnau-le-Lez",véhicule thermique/électrique,Runing,5,34
159,30256,Dumas,Odette,1960-12-22,Ventes,2023-04-08,45170,CDI,29,"2 Rue du Nord, 34920 Le Crès",véhicule thermique/électrique,NaN,0,29
160,94680,Pineau,Henri,1973-11-16,Marketing,2025-01-24,64180,CDD,26,"5 Av. de la Liberté, 34070 Montpellier",Vélo/Trottinette/Autres,Natation,5,31

# Création des fichiers de tables SQL

In [88]:
# Table département

data_departement = pd.DataFrame(data_rh_sport["BU"].unique(), columns=["nom_departement"])

data_departement = data_departement.reset_index().rename(columns={"index": "departement_id"})

data_departement.to_csv('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/tables_sql/departements.csv', index=False)

data_departement

   departement_id nom_departement
0               0       Marketing
1               1             R&D
2               2          Ventes
3               3         Support
4               4         Finance

In [89]:
# Table contrat

data_contrat = pd.DataFrame(data_rh_sport["Type de contrat"].unique(), columns=["nom_contrat"])

data_contrat = data_contrat.reset_index().rename(columns={"index": "contrat_id"})

data_contrat.to_csv('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/tables_sql/contrats.csv', index=False)

data_contrat

   contrat_id nom_contrat
0           0         CDI
1           1         CDD

In [90]:
# Table moyen de déplacement

data_moyen_deplacement = pd.DataFrame(data_rh_sport["Moyen de déplacement"].unique(), columns=["nom_moyen_deplacement"])

data_moyen_deplacement = data_moyen_deplacement.reset_index().rename(columns={"index": "moyen_deplacement_id"})

data_moyen_deplacement.to_csv('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/tables_sql/moyens_deplacement.csv', index=False)

data_moyen_deplacement

   moyen_deplacement_id          nom_moyen_deplacement
0                     0           Transports en commun
1                     1  véhicule thermique/électrique
2                     2                 Marche/running
3                     3        Vélo/Trottinette/Autres

In [129]:
# Création table employés avec les clés étrangères

data_employes = data_rh_sport[["ID salarié", "Nom", "Prénom", "Date de naissance", "Date d'embauche", "Type de contrat", "BU", "Moyen de déplacement", "Nombre de jours de CP", "Salaire brut", "Adresse du domicile"]]

data_employes = (
    data_employes
    .join(data_contrat.set_index("nom_contrat"), on="Type de contrat", how="right")
    .join(data_departement.set_index("nom_departement"), on="BU", how="right")
    .join(data_moyen_deplacement.set_index("nom_moyen_deplacement"), on="Moyen de déplacement", how="right")
    .drop(columns=["Type de contrat", "BU", "Moyen de déplacement"])
)


# Changement des noms de colonnes pour correspondre à la convention snake_case et à la bdd

data_employes = data_employes.rename(columns={
    "ID salarié": "employe_id",
    "Nom": "nom_employe",
    "Prénom": "prenom_employe",
    "Date de naissance": "date_naissance_employe",
    "BU": "departement_id",
    "Date d'embauche": "date_embauche",
    "Salaire brut": "salaire",
    "contrat_id": "type_contrat_id",
    "Adresse du domicile": "adresse",
    "Moyen de déplacement": "moyen_deplacement_id",
    "Nombre de jours de CP": "nombre_conges"
})
    
data_employes.to_csv('/home/romain/formation_data_engineer/Projet_12_SportDataSolution/data/tables_sql/employes.csv', index=False)

data_employes

,employe_id,nom_employe,prenom_employe,date_naissance_employe,date_embauche,nombre_conges,salaire,adresse,type_contrat_id,departement_id,moyen_deplacement_id
0,59019,Colin,Audrey,1990-07-06,2020-12-14,29,30940,"128 Rue du Port, 34000 Frontignan",0,0,0
86,34382,Payet,Capucine,1991-06-18,2022-12-04,25,48430,"151 Bd Victor Hugo, 34000 Montpellier",0,0,0
131,92440,Lacroix,Sébastien,1975-02-13,2024-09-27,27,35320,"369 Chem. du Thym, 34170 Castelnau-le-Lez",1,0,0
11,83440,Maillard,Augustin,1987-03-05,2023-10-27,28,31030,"38 Rue du Muscadet, 34090 Montpellier",0,1,0
42,37866,Gautier,Marine,1972-01-17,2021-09-10,27,50700,"4 Av. de la Paix, 34690 Fabrègues",0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
136,74171,Grondin,Bertrand,1988-04-26,2024-12-09,29,72520,"49 Pl. du Marché, 34250 Palavas-les-Flots",0,4,3
140,48154,Gosselin,Simone,1981-10-29,2022-09-01,25,65640,"Rue des Vignes, 34070 Montpellier",0,4,3
155,13780,Renard,Sylvain,1982-11-29,2024-04-11,25,60200,"56 Imp. Robespierre, 34130 Mauguio",0,4,3
156,18941,Guillou,Gilles,1986-12-23,2025-02-27,29,59910,"68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone",0,4,3
9,62296,Chauvin,Zakaria,1987-10-02,2024-11-23,26,68680,"31 Av. Grassion Cibrand, 34130 Mauguio",1,4,3

# Insertion des données dans les tables de la BDD

In [108]:
from sqlalchemy import create_engine
from sqlalchemy.orm import Session
import psycopg2

In [176]:
engine = create_engine("postgresql://postgres:roro@192.168.1.177:5432/SportDataSolution")

In [ ]:
# Push des données sur la table département

data_departement.to_sql(
    name="departement",   # nom de la table en base
    con=engine,
    if_exists="append",   # "append" = ajoute, "replace" = écrase
    index=False           # ne pas insérer l'index pandas comme colonne
)

5

In [ ]:
# Push des données sur la table contrat

data_contrat.to_sql(
    name="contrat",
    con=engine,
    if_exists="append", 
    index=False
)

2

In [135]:
# Push des données sur la table moyen de déplacement

data_moyen_deplacement.to_sql(
    name="moyen_deplacement",
    con=engine,
    if_exists="append",
    index=False
)

DatabaseError: Execution failed on sql 'INSERT INTO moyen_deplacement (moyen_deplacement_id, nom_moyen_deplacement) VALUES (:moyen_deplacement_id, :nom_moyen_deplacement)': (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "moyen_deplacement_pkey"
DETAIL:  Key (moyen_deplacement_id)=(0) already exists.

[SQL: INSERT INTO moyen_deplacement (moyen_deplacement_id, nom_moyen_deplacement) VALUES (%(moyen_deplacement_id__0)s, %(nom_moyen_deplacement__0)s), (%(moyen_deplacement_id__1)s, %(nom_moyen_deplacement__1)s), (%(moyen_deplacement_id__2)s, %(nom_moyen_deplacement__2)s), (%(moyen_deplacement_id__3)s, %(nom_moyen_deplacement__3)s)]
[parameters: {'nom_moyen_deplacement__0': 'Transports en commun', 'moyen_deplacement_id__0': 0, 'nom_moyen_deplacement__1': 'véhicule thermique/électrique', 'moyen_deplacement_id__1': 1, 'nom_moyen_deplacement__2': 'Marche/running', 'moyen_deplacement_id__2': 2, 'nom_moyen_deplacement__3': 'Vélo/Trottinette/Autres', 'moyen_deplacement_id__3': 3}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [131]:
# Push des données sur la table employes

data_employes.to_sql(
    name="salarie",
    con=engine,
    if_exists="append",
    index=False
)

DatabaseError: Execution failed on sql 'INSERT INTO salarie (employe_id, nom_employe, prenom_employe, date_naissance_employe, date_embauche, nombre_conges, salaire, adresse, type_contrat_id, departement_id, moyen_deplacement_id) VALUES (:employe_id, :nom_employe, :prenom_employe, :date_naissance_employe, :date_embauche, :nombre_conges, :salaire, :adresse, :type_contrat_id, :departement_id, :moyen_deplacement_id)': (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "salarie_pkey"
DETAIL:  Key (employe_id)=(59019) already exists.

[SQL: INSERT INTO salarie (employe_id, nom_employe, prenom_employe, date_naissance_employe, date_embauche, nombre_conges, salaire, adresse, type_contrat_id, departement_id, moyen_deplacement_id) VALUES (%(employe_id__0)s, %(nom_employe__0)s, %(prenom_emplo ... 41943 characters truncated ...  %(adresse__160)s, %(type_contrat_id__160)s, %(departement_id__160)s, %(moyen_deplacement_id__160)s)]
[parameters: {'employe_id__0': 59019, 'moyen_deplacement_id__0': 0, 'nom_employe__0': 'Colin', 'prenom_employe__0': 'Audrey', 'salaire__0': 30940, 'departement_id__0': 0, 'date_embauche__0': datetime.datetime(2020, 12, 14, 0, 0), 'adresse__0': '128 Rue du Port, 34000 Frontignan', 'type_contrat_id__0': 0, 'nombre_conges__0': 29, 'date_naissance_employe__0': datetime.datetime(1990, 7, 6, 0, 0), 'employe_id__1': 34382, 'moyen_deplacement_id__1': 0, 'nom_employe__1': 'Payet', 'prenom_employe__1': 'Capucine', 'salaire__1': 48430, 'departement_id__1': 0, 'date_embauche__1': datetime.datetime(2022, 12, 4, 0, 0), 'adresse__1': '151 Bd Victor Hugo, 34000 Montpellier', 'type_contrat_id__1': 0, 'nombre_conges__1': 25, 'date_naissance_employe__1': datetime.datetime(1991, 6, 18, 0, 0), 'employe_id__2': 92440, 'moyen_deplacement_id__2': 0, 'nom_employe__2': 'Lacroix', 'prenom_employe__2': 'Sébastien', 'salaire__2': 35320, 'departement_id__2': 0, 'date_embauche__2': datetime.datetime(2024, 9, 27, 0, 0), 'adresse__2': '369 Chem. du Thym, 34170 Castelnau-le-Lez', 'type_contrat_id__2': 1, 'nombre_conges__2': 27, 'date_naissance_employe__2': datetime.datetime(1975, 2, 13, 0, 0), 'employe_id__3': 83440, 'moyen_deplacement_id__3': 0, 'nom_employe__3': 'Maillard', 'prenom_employe__3': 'Augustin', 'salaire__3': 31030, 'departement_id__3': 1, 'date_embauche__3': datetime.datetime(2023, 10, 27, 0, 0), 'adresse__3': '38 Rue du Muscadet, 34090 Montpellier', 'type_contrat_id__3': 0, 'nombre_conges__3': 28, 'date_naissance_employe__3': datetime.datetime(1987, 3, 5, 0, 0), 'employe_id__4': 37866, 'moyen_deplacement_id__4': 0, 'nom_employe__4': 'Gautier', 'prenom_employe__4': 'Marine', 'salaire__4': 50700, 'departement_id__4': 1 ... 1671 parameters truncated ... 'departement_id__156': 4, 'date_embauche__156': datetime.datetime(2024, 12, 9, 0, 0), 'adresse__156': '49 Pl. du Marché, 34250 Palavas-les-Flots', 'type_contrat_id__156': 0, 'nombre_conges__156': 29, 'date_naissance_employe__156': datetime.datetime(1988, 4, 26, 0, 0), 'employe_id__157': 48154, 'moyen_deplacement_id__157': 3, 'nom_employe__157': 'Gosselin', 'prenom_employe__157': 'Simone', 'salaire__157': 65640, 'departement_id__157': 4, 'date_embauche__157': datetime.datetime(2022, 9, 1, 0, 0), 'adresse__157': 'Rue des Vignes, 34070 Montpellier', 'type_contrat_id__157': 0, 'nombre_conges__157': 25, 'date_naissance_employe__157': datetime.datetime(1981, 10, 29, 0, 0), 'employe_id__158': 13780, 'moyen_deplacement_id__158': 3, 'nom_employe__158': 'Renard', 'prenom_employe__158': 'Sylvain', 'salaire__158': 60200, 'departement_id__158': 4, 'date_embauche__158': datetime.datetime(2024, 4, 11, 0, 0), 'adresse__158': '56 Imp. Robespierre, 34130 Mauguio', 'type_contrat_id__158': 0, 'nombre_conges__158': 25, 'date_naissance_employe__158': datetime.datetime(1982, 11, 29, 0, 0), 'employe_id__159': 18941, 'moyen_deplacement_id__159': 3, 'nom_employe__159': 'Guillou', 'prenom_employe__159': 'Gilles', 'salaire__159': 59910, 'departement_id__159': 4, 'date_embauche__159': datetime.datetime(2025, 2, 27, 0, 0), 'adresse__159': '68 Bd des Écoles, 34750 Villeneuve-lès-Maguelone', 'type_contrat_id__159': 0, 'nombre_conges__159': 29, 'date_naissance_employe__159': datetime.datetime(1986, 12, 23, 0, 0), 'employe_id__160': 62296, 'moyen_deplacement_id__160': 3, 'nom_employe__160': 'Chauvin', 'prenom_employe__160': 'Zakaria', 'salaire__160': 68680, 'departement_id__160': 4, 'date_embauche__160': datetime.datetime(2024, 11, 23, 0, 0), 'adresse__160': '31 Av. Grassion Cibrand, 34130 Mauguio', 'type_contrat_id__160': 1, 'nombre_conges__160': 26, 'date_naissance_employe__160': datetime.datetime(1987, 10, 2, 0, 0)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

# Création de données STRAVA Like

In [174]:
# Fonction de création de données virtuelles

def StravaLikeDataGen(dataset_employes, nombre_activites):

    """""""""""""""""""""
    Fonction qui permet de générer des activités fictives sur le modèle de Strava, pour les salariés de l'entreprise.
     - dataset_employes : dataframe contenant les données des employés (doit contenir une colonne "employe_id" pour faire le lien avec les activités)
     - nombre_activites : nombre d'activités fictives à générer
    """""""""""""""""""""
    import random
    import pandas as pd

    sports = ["Course à pied", "Vélo", "Natation", "Marche", "Trotinette", "Voile"]
    id_employes = dataset_employes["employe_id"]
    distance = range(1,15)
    date = pd.date_range(start='2025-01-01', end='2025-12-31', freq='D')
    temps_exercice = range(600,3600)

    commentaires = [
        "Super séance, je me suis senti(e) en pleine forme !",
        "Pas mal, mais j'ai eu du mal à trouver mon rythme.",
        "A refaire très vite !",
        "J'ai adoré cette activité, c'était vraiment génial !"]
    
    print("Tentative d'insertion de", nombre_activites, "activités...")
    for _ in range(nombre_activites):
        activite = pd.DataFrame({
            "employe_id": [random.choice(id_employes)],
            "type_pratique_sportive": [random.choice(sports)],
            "distance": [random.choice(distance)],
            "date": [random.choice(date)],
            "temps_ecoule": [random.choice(temps_exercice)],
            "commentaire": [random.choice(commentaires)]
        })

        # Récupérer le dernier id présent dans la base
        last_id_query = "SELECT COALESCE(MAX(id_evenement_sportif), 0) FROM pratique_sport"
        last_id = pd.read_sql(last_id_query, con=engine).iloc[0, 0]

        activite.index = [last_id + 1]
        
        activite.to_sql(
            name="pratique_sport",
            con=engine,
            if_exists="append",
            index=True, 
            index_label = "id_evenement_sportif"
        )
    
    print(nombre_activites, "activités insérées avec succès")
    
    pass

In [180]:
StravaLikeDataGen(data_employes, 15)

Tentative d'insertion de 15 activités...
15 activités insérées avec succès